server:
  servlet:
    context-path: ${API_PREFIX:-/api}

spring:
  application.name: api
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID:-}
            client-secret: ${OAUTH_CLIENT_SECRET:-}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/recipe_manager?useSSL=false&gssEncMode=disable
    username: ${DB_USERNAME:recipe_user}
    password: ${DB_PASSWORD:db_pass}
    maximum-pool-size: ${DB_MAX_POOL_SIZE:10}
    minimum-idle: ${DB_MIN_IDLE:10}
    connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
    idle-timeout: ${DB_IDLE_TIMEOUT:600000}
    max-lifetime: ${DB_CONNECTION_MAX_LIFETIME:600000}
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: true
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/recipe_manager?useSSL=false&gssEncMode=disable
    user: ${DB_FLYWAY_USERNAME:recipe_user}
    password: ${DB_FLYWAY_PASSWORD:db_pass}

logging:
  level:
    root: ${DEBUG_LEVEL:INFO}
